# contents of clusters/{{ cluster.name }}/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "{{ cluster.name }}"
  namespace: "cluster-{{ cluster.name }}"
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: "{{ cluster.name }}"
    namespace: "cluster-{{ cluster.name }}"
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "{{ cluster.name }}-control-plane"
    namespace: "cluster-{{ cluster.name }}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: "{{ cluster.name }}"
  namespace: "cluster-{{ cluster.name }}"
